### ISSUE TITLE
proof-read-and-update

### ISSUE THREAD

**Issue by ClainRaniel** [LetsDefend/Blue-Team-Community#17]
Typo 
analyses -> analysis 

suggestion: 
FROM "In the following sections we will discuss why EDR is beneficial for us as SOC Analysts and how we can use it effectively." 
TO "In the following sections, we will discuss why EDR benefits SOC Analysts and how to use it effectively."

add a comma where the parentheses are.
On the right side**(,)** we can find general information about the device and displayable sections such as “Browser History”, “Network Connections”**(,)** and “Process List”.

Therefore**(,)** the device should be cut off from inner and outer networks until the security gaps are fixed and the device is usable again.
Issue location - SOC fundamentals > EDR endpoint detection response
https://app.letsdefend.io/training/lesson_detail/edr-endpoint-detection-and-response

**Comment by omergunal** [comment]
Updated
