### ISSUE TITLE
proof-read-and-update

### ISSUE THREAD

**Issue by ClainRaniel** [LetsDefend/Blue-Team-Community#18]
SOC Fundamentals > SOAR 

Suggestion
**From** "it enables the security products and tools within an environment to work together and therefore makes the SOC team members' jobs easier. For example it will automatically perform a search for the source IP of a SIEM alert in Virustotal and so it lightens the load of the SOC analyst."
**TO** "It allows security products and tools in an environment to work with one another, making the responsibilities of SOC team members easier. For example, it will automatically search Virustotal for the source IP of a SIEM alert, reducing the workload of the SOC analyst."

FROM "These playbooks help us conduct an analysis because we can follow the instructions even though we don’t know or remember all the steps of the analysis."
TO "We can conduct an analysis using these playbooks since we can follow the steps even if we don't know or recall all of the procedures."

TYPO on playbook section -
"Additionally, these playbooks help the whole SOC team to conduct their **analyses** (analysis) on the same plane. "

Add comma
When we click on any open case**(,)** we see an automatically assigned playbook. We can examine the related SIEM (Monitoring) alert following this playbook.

**Comment by omergunal** [comment]
updated
