### ISSUE TITLE
Proof Read and Update

### ISSUE THREAD

**Issue by ClainRaniel** [LetsDefend/Blue-Team-Community#19]
**SOC146 - Phishing Mail Detected - Excel 4.0 Macros**
<img width="557" alt="image" src="https://user-images.githubusercontent.com/48438440/232264454-c4d586ec-6762-42b2-a06d-7fc32864250f.png">

May cause confusion:
the instruction says to click "Yes" and "No" but the buttons are labeled "not opened" and "opened"

It is understandable that yes means opened and no means not opened but for the sake of uniformity, I suggest changing the label or the instruction.

**Comment by omergunal** [comment]
Thanks, updated.
