### ISSUE TITLE
Grammar on Windows's Directory Structure Page

### ISSUE THREAD

**Issue by chrisbobek** [LetsDefend/Blue-Team-Community#22]
From https://app.letsdefend.io/training/lesson_detail/directory-structure:
"We have covered how the directory structure of Windows is and the directories of Windows own created after the first installation. In the next part of the training, "Command Line" will be explained practically."

This reads better:
This section examined Windows's directory structure and looked at the directories that are created during installation. In the next section, we provide a practical explanation of the command line.

**Comment by omergunal** [comment]
Updated, thanks!
