### ISSUE TITLE
SOC Fundamentals Quiz

### ISSUE THREAD

**Issue by omergunal** [LetsDefend/Blue-Team-Community#6]
There is a lesson about SOC Fundamentals but it has no quiz. (https://app.letsdefend.io/training/lessons/soc-fundamentals)

Steps:

1. Prepare 10 questions related to this course (https://app.letsdefend.io/training/lessons/soc-fundamentals)
1.1. Each question should has 4 options
1.2. Each question has only one correct answer
2. Highlight the correct answers
3. Upload everything on Google Drive and send the link to us as a comment or to [info@letsdefend.io](mailto:info@letsdefend.io)
4. LetsDefend team will review your materials. If necessary, will do some edits for a better format then release it.

**Comment by Blue-Atom-10101** [comment]
I just sent you a quiz proposal.

**Comment by omergunal** [comment]
https://app.letsdefend.io/quiz/quiz/soc-fundamentals/
